package constants

const (
	ValidationRequired        = "required"
	ValidationMax             = "max"
	ValidationOneOf           = "oneof"
	ValidationMin             = "min"
	ValidationEmail           = "email"
	ValidationBase64          = "base64"
	ValidationHasDigit        = "hasDigit"
	ValidationHasUpper        = "hasUpper"
	ValidationHasLower        = "hasLower"
	ValidationHasSpecialChars = "hasSpecialChars"
	ValidationEqfield         = "eqfield"
	ValidationNoHandphone     = "e164"
	ValidationGtfield         = "gtfield"
	ValidationNumber          = "number"
	ValidationUUID            = "uuid4"
	ValidationDatetime        = "datetime"
	ValidationDateGTEField    = "yyyymmdd_gtefield"
	ValidationGtefield        = "gtefield"
	ValidationFileSize        = "fileSize"
	ValidationGt              = "gt"
	ValidationMIMEType        = "mimeType"
	ValidationUrl             = "url"
	ValidationDateLessThan    = "validateDateLessThan"
	ValidationRequiredWithout = "required_without"
	ValidationDate            = "date"
	ValidationTime            = "time"
	ValidationDateGTENow      = "date_gte_now"
	ValidationTimeGTENow      = "time_gte_now"
	ValidationPhoneNumber     = "phoneNumber"
	ValidationUnique          = "unique"
)
