// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/crypto/crypto.go

// Package mock_utils is a generated GoMock package.
package mock_utils

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCustomCrypto is a mock of CustomCrypto interface.
type MockCustomCrypto struct {
	ctrl     *gomock.Controller
	recorder *MockCustomCryptoMockRecorder
}

// MockCustomCryptoMockRecorder is the mock recorder for MockCustomCrypto.
type MockCustomCryptoMockRecorder struct {
	mock *MockCustomCrypto
}

// NewMockCustomCrypto creates a new mock instance.
func NewMockCustomCrypto(ctrl *gomock.Controller) *MockCustomCrypto {
	mock := &MockCustomCrypto{ctrl: ctrl}
	mock.recorder = &MockCustomCryptoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomCrypto) EXPECT() *MockCustomCryptoMockRecorder {
	return m.recorder
}

// AesDecryptGcmNoPadding mocks base method.
func (m *MockCustomCrypto) AesDecryptGcmNoPadding(aesKey, encryptedBase64 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AesDecryptGcmNoPadding", aesKey, encryptedBase64)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AesDecryptGcmNoPadding indicates an expected call of AesDecryptGcmNoPadding.
func (mr *MockCustomCryptoMockRecorder) AesDecryptGcmNoPadding(aesKey, encryptedBase64 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AesDecryptGcmNoPadding", reflect.TypeOf((*MockCustomCrypto)(nil).AesDecryptGcmNoPadding), aesKey, encryptedBase64)
}

// AesEncryptGcmNoPadding mocks base method.
func (m *MockCustomCrypto) AesEncryptGcmNoPadding(aesKey, strIn string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AesEncryptGcmNoPadding", aesKey, strIn)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AesEncryptGcmNoPadding indicates an expected call of AesEncryptGcmNoPadding.
func (mr *MockCustomCryptoMockRecorder) AesEncryptGcmNoPadding(aesKey, strIn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AesEncryptGcmNoPadding", reflect.TypeOf((*MockCustomCrypto)(nil).AesEncryptGcmNoPadding), aesKey, strIn)
}

// GenerateCEK mocks base method.
func (m *MockCustomCrypto) GenerateCEK(privateKeyBase64, publicKeyBase64 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCEK", privateKeyBase64, publicKeyBase64)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCEK indicates an expected call of GenerateCEK.
func (mr *MockCustomCryptoMockRecorder) GenerateCEK(privateKeyBase64, publicKeyBase64 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCEK", reflect.TypeOf((*MockCustomCrypto)(nil).GenerateCEK), privateKeyBase64, publicKeyBase64)
}
